### ISSUE TITLE
same interface such as gleam_pgo and sqlight?

### ISSUE THREAD

**Issue by inoas** [VioletBuse/gmysql#1]
would that be possible?
right now at least the Param type variants are missing

**Comment by violetbuse** [comment]
I'm considering it, but what is the benefit of a function for each param type rather than one that takes anything and returns a param? Right now it's super simple, you just pass anything to the `to_param` function, and given that there's no programming with modules in gleam like you could in ocaml.

**Comment by inoas** [comment]
@VioletBuse I'd suggest to discuss that with @lpil so that common ground can maybe reached.

There is also https://hex.pm/packages/based

**Comment by inoas** [comment]
I am trying to integrate your mysql adapter into unit tests of https://hexdocs.pm/cake/index.html atm :)

**Comment by violetbuse** [comment]
right now, the pgo and sqlight interfaces aren't identical either, so I made a change in v1.2.0 to bring it *more* in line with those, but supporting the same interface can't happen until they share one as well, obviously.

the existence of the based package is nice, I was actually considering building that myself, for integration into my migration runner, so it's nice to see that that already exists.

for now, my priority is to build a connection pooler and retry system, but if you have any changes you'd like to see, I'm happy to make them.

<3
